#!/usr/bin/env node

var {{camelCmdName}} = require('../cmds/{{cmdName}}')
var commander = require('commander')

commander
	.version('0.0.1')
	.arguments('{{syntax}}')
	.action({{camelCmdName}}.run)

commander.parse(process.argv)